### ISSUE TITLE
Series info page

### ISSUE THREAD

**Issue by li-btu** [leerzeichen7/nice#10]
![image](https://user-images.githubusercontent.com/94308833/147162394-6bc6af9f-7df9-4d9d-b98d-d636dceb96ea.png)

@a1d4c7 @leerzeichen7 I have a few questions regarding the series info page layout.
1. Are these two layouts both referring to the *-info.html series info page?
2. Is the "Background Info1" a button or a text area? If it's a button, where is it linked to? Is it necessary to have it?
3. Which layout should we use for the series info page? Upper one or lower one? Same for all of the series?
4. We have no text contents for Riots and Marvel, but only pictures. Is it good enough to put all the pictures in their series info page? Otherwise, please provide text contents for "General information" and "Detailed information".
5. For Arcane, Loki, Wanda Vision and the Falcon, you have only provided their general information. Detailed information is still missing. Please let us know if it's necessary to have it.

**Comment by li-btu** [comment]
Sorry, please ignore Question 2. I found the answer in your website design diagram.

**Comment by a1d4c7** [comment]
The first piture is for all of the series info pages. The second Picture is the background info page (Marvel and Riot). You get to it by using "Background Info1" button. For the Riot info page you have listed all the games/pictures we already provided. We want you to put some text next to each of them (we provide the text soon). For the Marvel info page we only want the picture of the timeline for now.

**Comment by a1d4c7** [comment]
i commited the missing text for the riot info page in the main branch

**Comment by li-btu** [comment]
@a1d4c7 I've added the text to riot info page. Please check.
If there is no more text/ info to be provided, I will close this issue.
