### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by oxySmith** [leerzeichen7/nice#11]
@leerzeichen7  Could you please set up GitHub Pages for the project? I think, I do not have permissions to manage settings. It would be very convenient to browse the pages using a github link  for further review.

**Comment by leerzeichen7** [comment]
GitHub Pages should now work for the project

**Comment by oxySmith** [comment]
@leerzeichen7 @li-btu  @a1d4c7 Link for the project
https://leerzeichen7.github.io/nice/assignment-2b/docs/home.html
