### ISSUE TITLE
GitHub Pages deployment failed

### ISSUE THREAD

**Issue by li-btu** [leerzeichen7/nice#12]
@a1d4c7 @leerzeichen7 Hi, we have updated all the webpages but found that the GitHub pages auto deployment workflow is broken, I have no idea why. (see https://github.com/leerzeichen7/nice/actions/workflows/pages/pages-build-deployment) Could you please help fix it? Thanks!

**Comment by oxySmith** [comment]
It seems that it looked up for a css class in a particular folder but didnt find the file   
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/style.scss':
                    No such file or directory @ dir_chdir - /github/workspace/docs

**Comment by leerzeichen7** [comment]
I just deactivated GitHub pages for the repository and then activated it again.
But it looks like it didn't fix the workflow problem.

Unfortunately there aren't any settings for GitHub pages.
Maybe there is something wrong with the files in the repo

**Comment by leerzeichen7** [comment]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/84912693/147918074-55426855-0e70-4309-a1b1-bf8d6ef39a0a.png">

**Comment by leerzeichen7** [comment]
It looks like there is a file missing

**Comment by li-btu** [comment]
I tried to copy the css file to assets/css as style.scss but it didn't work. It is still the same error message. I guess at the moment you may only review our updates by pulling the code.

> <img alt="image" width="929" src="https://user-images.githubusercontent.com/84912693/147918074-55426855-0e70-4309-a1b1-bf8d6ef39a0a.png">

**Comment by li-btu** [comment]
@leerzeichen7 Could you please help to change the settings following the guide below, to use the develop branch docs folder as the publishing source? Thanks.
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

**Comment by li-btu** [comment]
@leerzeichen7 Hi, I tried to build the pages in a copy of your repository and I found that you have to use the following settings for the Pages source to get a successful build:
Source branch: main
Source folder: /(root)

Could you please help to configure that? The required steps are in the link below.
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#choosing-a-publishing-source

**Comment by leerzeichen7** [comment]
I adjusted the settings and now the build was successful.

**Comment by li-btu** [comment]
Perfect. Thanks a lot. We may all now check the website on https://leerzeichen7.github.io/nice/assignment-2b/docs/home.html
