### ISSUE TITLE
Review all webpages

### ISSUE THREAD

**Issue by li-btu** [leerzeichen7/nice#13]
@a1d4c7 @leerzeichen7 
We have done the implementation of all webpages. Please review them and let us know if anything needs to be changed to fulfil your requirements. Unfortunately GitHub Pages still fails to build, so please pull the code from the develop branch before we could fix it. Thank you!
@oxySmith

**Comment by li-btu** [comment]
I have forked your repository to my new repository so that you can review the webpages on Pages with the link below.
https://li-btu.github.io/nice/assignment-2b/docs/home.html

**Comment by a1d4c7** [comment]
All pages look pretty good. We are happy with how they turned out on mobile and desktop.
