### ISSUE TITLE
WebPages

### ISSUE THREAD

**Issue by a1d4c7** [leerzeichen7/nice#2]
I have uploaded a first version of our website-design-diagram. Should we make our NewsPage + Newsletter an extra webpage that is accessible from our home page or just include it directly in our homepage?

**Comment by leerzeichen7** [comment]
We can include it directly in our Homepage, I guess.

**Comment by Ked00** [comment]
Can I contribute?

**Comment by leerzeichen7** [comment]
Of course, I added you as a collaborator to our repository

**Comment by leerzeichen7** [comment]
What's your name and who is your partner?

**Comment by Ked00** [comment]
i dont have a partner
