### ISSUE TITLE
Repository access

### ISSUE THREAD

**Issue by oxySmith** [leerzeichen7/nice#4]
Hello, could you please add us: @li-btu and @oxySmith as contributors?

**Comment by leerzeichen7** [comment]
I invited you both to our repository

**Comment by oxySmith** [comment]
Thank you!

**Comment by oxySmith** [comment]
Could you please reiissue an invitation? I get 403 error unfortunatelly, i will try once again

**Comment by li-btu** [comment]
I noticed that we are only invited to be collaborators but not contributors. Could you please grant us contributor role, so that our commit history will be shown on the insight page? Thanks

**Comment by oxySmith** [comment]
Worked for me, thanks!

**Comment by leerzeichen7** [comment]
No problem.

Regarding to the other question I don't know how to grant contributor role. I think you'll get the role automatically if you do a commit.

**Comment by li-btu** [comment]
The current collaborator role should be enough for us to do changes and show commit history. Thanks
