### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by li-btu** [leerzeichen7/nice#5]
@a1d4c7 @leerzeichen7 I saw that there are 2 color schemes provided. Which one do you want us to use? Could you also provide us the HTML color codes? Or is it fine for us to use colors similar to them? Thanks.

**Comment by leerzeichen7** [comment]
ColorScheme.png is the scheme we selected.
The HTML color codes are the following: 
484848 grey
FFFFFF white
A1D4C7 "blue"
FF6262 "red"

**Comment by li-btu** [comment]
Thank you. We will use ColorScheme.png and the color codes you provided above.
