### ISSUE TITLE
Review prototype

### ISSUE THREAD

**Issue by li-btu** [leerzeichen7/nice#9]
@a1d4c7 @leerzeichen7
We have finished the prototype of home.html and overview.html for both desktop and mobile use. Could you please pull the latest code in the develop branch and give us a review? Please let us know if anything needs to be changed preferably soon. Thanks!

**Comment by a1d4c7** [comment]
Both pages look pretty good. We are happy with how they turned out. But we could only check it for desktop. How does it work on mobile? How do I check it there?

**Comment by li-btu** [comment]
Thanks! Glad to hear that.
You may make use of GitHub Pages on your repository (as requested in #11) so you can open it on mobile devices easily. https://leerzeichen7.github.io/nice/assignment-2b/docs/home.html
